version: "3.9"
services:
  nginx:
    image: nginx:latest
    ports:
      - 8082:80
    volumes:
      - ./src/:/var/www/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build: ./src/
    env_file:
      - ./.env
    volumes:
      - ./src/:/var/www/
    links:
      - mysql
  mysql:
    image: mysql:8.0
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/image:/var/lib/mysql
    ports:
      - 3306:3306
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}