version: "3.9"
services:
  nginx:
    image: nginx:latest
    ports:
      - 8082:80
    volumes:
      - ./src/:/var/www/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    image: php:8-fpm
    volumes:
      - ./src/:/var/www/
  mysql:
    image: mysql:8.0
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql